### ISSUE TITLE
Don't report StringPropertyLengthBoundsRule if property has enum

### ISSUE THREAD

**Issue by pdc** [zalando/zally#1137]
When a property of type string has an enum setting it does not make sense to specify minimum and maximum length. 

Reproduce with an object in a body or response like this:
```yaml
type: object
properties:
  fooBar:
    type: string
    enum: [foo, bar]
```

Gets complaint from rule S007 SHOULD Define bounds for lengths of string properties 

Expected: 
- Don’t insist on adding `minLength` and `maxLength`
- In fact it might make sense to complain if they are present
