### ISSUE TITLE
Zally doesn't catch all open-api syntax errors.

### ISSUE THREAD

**Issue by marekhudyma** [zalando/zally#1169]
In some situations, Zally doesn't catch all open-api syntax errors.
To make sure all cases are caught I use: `https://editor.swagger.io/`. 
Example - in this endpoint I didn't specify `schema: type: string` for header and Zally didn't complain about it. 
`https://editor.swagger.io/` detected it as an error. 
```
paths:
  /endpoint:
    post:
      summary: |
        Some summary.
      security:
        - oauth2: ["uid"]
      parameters:
        - name: X-HEADER-ID
          description: |
            Header description
          in: header
          schema:  <-- Zally didn't detect missing of this line
            type: string  <-- Zally didn't detect missing of this line
          required: false
```
