### ISSUE TITLE
Extend "x-zally-ignore" to support exclusion reasons

### ISSUE THREAD

**Issue by vadeg** [zalando/zally#1261]
`x-zally-ignore` extension allows to skip rules check of specific schema parts. 

For example the following extension usage
```
openapi: 3.0.0
servers:
  - url: http://example.com
    x-zally-ignore: [Rule-123]
```
allows not to validate `Server` object with the `url = http://example.com`. 

`x-zally-ignore` has a format of an array of strings. I propose to extend the format and support array of objects, where the key is a rule id and value is a reason why this exception has been applied. [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#specification-extensions) supports objects.

### Example

```
servers:
  - url: http://example.com
    x-zally-ignore: 
      - Rule-123: Not relevant for our service
      - Rule-789: Not applicable
```
