### ISSUE TITLE
Support api_key security scheme

### ISSUE THREAD

**Issue by Rajesh-Narayanappa87** [zalando/zally#1407]
Hi Team,
We have spec file having apiKey param.. Example is below. Linter is complaining security issue though required apiKey details exist.. On checking, we found only OAUTH2 is supported. Is it possible to add support for apiKey Please?

```
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
      ApiKeyAuth:
        type: apiKey
        name: api_key
        in: header
```
