### ISSUE TITLE
unspecific error message when scope names don't fit the naming schema

### ISSUE THREAD

**Issue by ePaul** [zalando/zally#1456]
## Current behavior

When an API has security schemes with scopes which don't fit the naming schema defined in [rule 225](https://opensource.zalando.com/restful-api-guidelines/#225), Zally reports an unspecific violation for rule 105.

```yaml
...
paths:
  '/example':
   get:
     security:
       foo:
         - example/read
     ...
components:
  securitySchemes:
    foo:
      type: oauth2
      description: Example OAuth scheme
      flows:
        clientCredentials:
          tokenUrl: https://api.example.com/oauth/token
          scopes:
            example/read: Read access to this API
            example/write: Write access to this API
```
(The correct scope names would be `example.read` and `example.write`.)

## Expected behavior

Instead, there should be a violation for [rule 225](https://opensource.zalando.com/restful-api-guidelines/#225), telling that the rule name is not fitting naming convention.

A violation for [rule 105](https://opensource.zalando.com/restful-api-guidelines/#105) is still applicable if there is an endpoint without any scope assigned.
