### ISSUE TITLE
Misleading error message for invalid OAuth2 rule

### ISSUE THREAD

**Issue by KaiStapel** [zalando/zally#690]
The following swagger snipped is invalid:
```
securityDefinitions:
  oauth2:
    type: oauth2
    authorizationUrl: 'https://auth.zalando.com/oauth2/authorize'
    flow: application
    scopes:
      uid: Employee scope
```
because for `flow: application` a `tokenUrl` is required instead of a `authorizationUrl`. However, the error message reads as follows:
```
MUST – Provide API Specification using OpenAPI
instance failed to match exactly one schema of: #/definitions/basicAuthenticationSecurity; #/definitions/apiKeySecurity; #/definitions/oauth2ImplicitSecurity; #/definitions/oauth2PasswordSecurity; #/definitions/oauth2ApplicationSecurity; #/definitions/oauth2AccessCodeSecurity

Rule: https://zalando.github.io/restful-api-guidelines/#101

Paths:

/securityDefinitions/oauth2
```

This makes it really hard to identify the actual problem.

The message should at least point to https://zalando.github.io/restful-api-guidelines/#104

This might be related to #656
