### ISSUE TITLE
New Check for Zalando Rule [151]: MAY use ProblemJson as default response schema

### ISSUE THREAD

**Issue by ZalandoGhPages** [zalando/zally#700]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/369 introduces changes which are relevant to the Zally project.

**Comment by maxim-tschumak** [comment]
We should check for:
```
  default:
    description: a specific error occurred - see status code for more information.
    schema:
      $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
```
for each endpoint. This should be a "MAY" violation only.
