### ISSUE TITLE
export docker images for client and server

### ISSUE THREAD

**Issue by sebastiendementen** [zalando/zally#761]
to ease the use of Zally :-)
this could be done at the end of the CI pipe maybe

**Comment by roxspring** [comment]
Would be particularly awesome if, via #560, a custom jar of rules could be mounted into the server.

**Comment by maxim-tschumak** [comment]
@vadeg no, but there is the [Zalando open-source Docker registry](registry.opensource.zalan.do) :)

**Comment by roxspring** [comment]
Just had a play with GitHub Packages (as @zeitlinger [mentioned in #964](https://github.com/zalando/zally/issues/964#issuecomment-558066199)). Publishing is actually pretty straight forward and would just require a repo owner to enable actions and establish a secret GITHUB_USER and the following `.github/workflows/docker-publish.yml`

```
name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Server Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: zalando/zally/server
        workdir: ./server
        username: ${{ secrets.GITHUB_USER }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com

```

... but the benefits are completely undermined by the Docker registry [requiring credentials to `docker pull` the image](https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782). If we want people to just `docker pull somehost/zalando/zally/server` then Docker Hub or Zalando's own repository look to be preferrable.
