### ISSUE TITLE
Path parameter case false-positive

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#884]
Zally produces this violation:
```
Path parameter 'business-partner-id' does not match snake_case ([a-z][a-z0-9]*(?:_[a-z0-9]+)*) but seems to be kebab-case
```

for the following specificaiton:
```
'/item-quantity-snapshots/{business-partner-id}':
    get:
      description: |
        Returns most recent item quantity snapshot of a given partner.
      security:
        - oauth2: [zfs-inventory.item-quantity.read]
      parameters:
        - name: business-partner-id
          in: path
          required: true
          type: string
          format: uuid
          description: |
            UUID identifing the business partner.
```

The Guideline explicitely allows such path parameter names.
